services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: Dockerfile
    buildCommand: "composer install && npm install && npm run prod && php artisan migrate --force"
    startCommand: "php-fpm"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:YB7GzJ/NfAzzCrX/Bvg6SSN8cnvGITXeCNHFAhPN76A=
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
