version: 2.1

executors:
  php-executor:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/repo

jobs:
  install_dependencies:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: composer install --no-dev --prefer-dist --no-interaction
      - run:
          name: Install Node.js Dependencies
          command: npm install

  build_frontend:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Build React Frontend
          command: npm run dev

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Run Laravel Tests
          command: ./vendor/bin/phpunit

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - install_dependencies
      - build_frontend:
          requires:
            - install_dependencies
      - run_tests:
          requires:
            - build_frontend
